/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ProductsVariablesQuery = {
    includeDescription: boolean;
};
export type ProductsVariablesQueryVariables = {};
